output_spool_lines = 99999
prompt_prefix = "\\[\\$(tput sc)\\eD\\eD\\e[2A\\e[1;\\$((\\$(tput lines) - 1))r\\e[\\$(tput lines);1H\\e[48;5;015;38;5;160m\\]shpool:[$SHPOOL_SESSION_NAME]\\[\\e[K\\e[0m\\$(tput rc)\\]"
